version: '3'

services:
  db:
    image: postgres:latest
    networks:
      - django_net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: django_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  django:
    build: .
    command: python manage.py runserver 0.0.0.0:80
    networks:
      - django_net
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    networks:
      - django_net
    ports:
      - "8888:80"
    environment:
      TZ: Asia/Tokyo
      PGADMIN_DEFAULT_EMAIL: 'aaa@bbb.ccc'
      PGADMIN_DEFAULT_PASSWORD: 'password'

networks:
    default:
        external:
            name: bridge
    django_net:
        driver: bridge